{'n_user-flow_dashboard': 1,
'n_user-flow_navigate': 3,
'n_user-flow_navigate_dashboard': 1,
'n_user-flow_navigate_trade': 1,
'n_user-flow_navigate_transactions': 1,
'n_user-flow_trade': 1,
'n_user-flow_transactions': 1,
'n_user-interaction_click': 4,
'n_user-interaction_click_switch-product-type-trxusd': 2,
'n_user-interaction_click_switch-product-type-zrxusd': 2,
'n_user-interaction_switch-product-type-trxusd': 2,
'n_user-interaction_switch-product-type-zrxusd': 2,
'n_events': 7,
'request': {'_id': ObjectId('5b50d4215fc77c000af67b6d'),
'created': Timestamp('2018-07-19 18:10:41.558000+0000', tz='<bson.tz_util.FixedOffset object at 0x7f32f0306be0>'),
'category_action_label': 'interac_request_interac-confirm',
'category_action': 'interac_request',
'category_label': 'interac_interac-confirm',
'event_category': 'interac',
'event_action': 'request',
'event_label': 'interac-confirm',
'user_email': 'mung@einstein.exchange',
'user_ip': '172.255.50.90',
'transaction_type': 'interac',
'device_info': 'mozilla/5.0 (macintosh; intel mac os x 10_13_3) applewebkit/537.36 (khtml,like gecko) chrome/67.0.3396.87 safari/537.36'}}